export const sensitiveWords = [
 'kontol', 'memek', 'anjing', 'babi', 'jancok', 'sialan', 'bangsat', 'bodoh', 'idiot', 'pukimak', 
  'pelacur', 'tai', 'setan', 'anjir', 'goblok', 'perek', 'goblok', 'fuck', 'shit', 'bitch', 
  'cunt', 'dick', 'whore', 'slut', 'faggot','nigga','nigger', 'asshole', 'bastard', 'motherfucker', 
  'babi ngepet', 'pecundang', 'gila', 'gantung diri', 'penipu', 'toilet', 'berengsek', 'ngentot', 
  'kampret', 'pencabul', 'bersetubuh', 'cerai', 'seks', 
  'pelacuran', 'asusu', 'bandel', 'jembut', 'balon', 'belakang',
   // Variations of sensitive words
   'kntl', 'kntol', 'kontl', 'kont0l', 'k0ntol', 'k0ntl', 'knt0l', 
   'm3m3k', 'memeck', 'm3mek', 'memek', 
   'b4bi', 'babi', 'b@bi', 'b4b1', 'b4b1', 
   'j4ncok', 'jancok', 'jancok', 'j@nck', 
   'b@ngsat', 'bngsat', 'bng5at', 'b@ng5at',
   't@i', 'ta1', 'tai', 'ta1', 
   '5etan', 'setan', '5tan', 'se7an',
   'anjiing', 'anjing', 'anj1ng', '4njing', 
   'g0bl0k', 'goblok', 'g0bl0k', 'gbl0k', 
   'perek', 'p3r3k', 'pr3k', 'prk', 'p3r3ck', 
   'f0ck', 'fck', 'f@ck', 'phuck', 
   'sh!t', 'sh1t', 'shytt', 'sh!tt',
   'b!tch', 'b1tch', 'b!t', 'bitch',
   'cunt', 'cunt1', 'cunt0', 'cunt3', 
   'd1ck', 'dick', 'd!ck', 'd1k',
   'wh0r3', 'wh0re', 'w0re', 'wh0r3',
   'slut', 'slutty', '5lut', 'slut1', 'slut3',
   'fagg0t', 'faggot', 'f@g0t', 'f@g', 
   'n1gger', 'nigger', 'n!gger', 'n!ggr', 
   'as5hole', 'asshole', 'as$hole', 'as$h0le',
   'b@stard', 'bastard', 'b@stard', 'b4stard', 
   'm0therfucker', 'motherfucker', 'mthrfckr', 'mthrfuckr',
   'babi ngepet', 'babi ngep3t', 'babi ngep3t', 
   'pecund4ng', 'pecundang', 'p3cundang', 
   'g!la', 'gila', 'g1la', 'g!1a', 
   'g4ntung diri', 'gantung diri', 'g4ntung d!ri', 
   'pen!pu', 'penipu', 'pen1pu',
   't01let', 'toilet', 't0ilet', 't01l3t',
   'berengs3k', 'berengsek', 'b3r3ngs3k', 'brngsek',
   'ng3ntot', 'ngentot', 'ng3nt0t', 'ng3nt0t', 
   'kampr3t', 'kampret', 'k@mpr3t',
   'p3nc@bul', 'pencabul', 'p3ncabul',
   'h4ram', 'haram', 'h@ram', 'h4r4m', 
   'k0t0r', 'kotor', 'k0t0r', 'k@t0r', 
   'pukul4n', 'pukulan', 'pukul@n', 'pukulan',
   'b3rs3tubuh', 'bersetubuh', 'b3rs3tubuh', 'b3rs3tubuh', 
  ];
  
  export function isSensitiveContentPresent(text) {
    const regex = new RegExp(sensitiveWords.join('|'), 'i');
    return regex.test(text);
  }  